### ISSUE TITLE
Deleting a device fails

### ISSUE THREAD

**Issue by ds2600** [ds2600/cab-gui-public#6]
Deleting a device fails if previous backups made, due to foreign key reference in Backups table.
`2020-05-03 10:01:54 - cab-gui: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails in /var/www/html/admin/dist/classes/core.class.php:33
2020-05-03 10:01:54 - cab-gui: Stack trace:
2020-05-03 10:01:54 - cab-gui: #0 /var/www/html/admin/dist/classes/core.class.php(33): PDOStatement->execute(Array)
2020-05-03 10:01:54 - cab-gui: #1 /var/www/html/admin/dist/classes/device.class.php(266): Core->run('DELETE FROM Aut...', Array)
2020-05-03 10:01:54 - cab-gui: #2 /var/www/html/admin/dist/pages/delete.pages.php(16): Device->rmDev('39')
2020-05-03 10:01:54 - cab-gui: #3 /var/www/html/admin/dist/index.php(15): include('/var/www/html/a...')
2020-05-03 10:01:54 - cab-gui: #4 {main}`

**Comment by ds2600** [comment]
This _may_ be fixed with XML transition.

**Comment by ds2600** [comment]
Currently must "delete device" twice, first time will delete associated backup files, second time deletes the device.

**Comment by ds2600** [comment]
Issue resolved.
